DEFAULTS: &DEFAULTS
  adapter: mysql
  encoding: utf8
  username: root
  password:
  host: localhost


development:
  database: google-is-your-new-mom_development
  <<: *DEFAULTS

production:
  database: google-is-your-new-mom_production
  password: 55zxcv55
  <<: *DEFAULTS

# Do not set this db to the same as development or production.
test:
  database: google-is-your-new-mom_test
  <<: *DEFAULTS

